### ISSUE TITLE
SpecDM Compatibility

### ISSUE THREAD

**Issue by MinIsMin** [Zaratusa/gmod_stuff#4]
If the server uses the addon 'Spectator Deathmatch' and a player joins the Deathmatch after his death and leaves the server the server displays he was still alive.

To check whether a player is in SpecDM, use the following code (also works for server without SpecDM):

`if file.Exists("sh_spectator_deathmatch.lua", "LUA") then
	if (LocalPlayer():IsGhost()) then
	print('A dead player left the server') -- Insert message to display the role and say he's dead.
	end
end`

**Comment by Zaratusa** [comment]
Thanks for the advice, should be fixed now.
