### ISSUE TITLE
Jihad SphereDamage Broken

### ISSUE THREAD

**Issue by Violat0r** [Zaratusa/gmod_stuff#5]
No matter how far you are from the explosion, the damage is always the same when it comes through a wall. The damage given is always 125. The main issue I have is this line dmg = -0.01 * (d^2) + 125 where 125 is the value damage given to a player through a wall. I can change 125 to 1 or 50 and it will always give that amount of damage to a player without regards to -0.01 * (d^2). It is like the rest of the code in this function doesn't even work it might as well be dmg = 125.

**Comment by Zaratusa** [comment]
Seems weird, because I've taken the code from the original C4. I've also tested some damage variations as I've reworked  it and haven't that problems.

**Comment by Violat0r** [comment]
I am not seeing any of that code inside the current C4 lua. I think the issue is that `diff = center - ent:GetPos() d = diff:Dot(diff)` isn't working as intended and it still stays nil.

**Comment by Zaratusa** [comment]
The code I've used is in the "\terrortown\entities\entities\ttt_c4\shared.lua". I'll see in the next days, if I get the same problem.

**Comment by Zaratusa** [comment]
So I've tested it and what you meant, that the damage is always 125, is true because the distance to yourself is 0 and though the damage is always 125. You have to test it with at least two players. That's what I did and it works correctly.

**Comment by Violat0r** [comment]
Shouldn't the damage scale depending how are you from the blast?

**Comment by Zaratusa** [comment]
That's right and that's excatly what happens. But when you just test it alone, it's always 125 because the distance to yourself is always 0.

**Comment by Violat0r** [comment]
I was testing it with others. Set it to a number such as 50 and you will always take 50 damage when someone else jihads through a wall.

**Comment by Zaratusa** [comment]
I've tested it and it worked fine for me. Maybe they were not far enough away for the fall off?

**Comment by Violat0r** [comment]
It is possible though I am sure we tested it at different distances with the same damage occurring. If you wanna hop onto a test server together we can test it real quick together.

**Comment by Zaratusa** [comment]
Yeah can you send me an IP or so?

**Comment by Violat0r** [comment]
162.248.88.13:27015 pass testing

**Comment by Zaratusa** [comment]
So what are the results?

**Comment by Violat0r** [comment]
50 HP when changed from 125 to 50. There is no scaling just stops damaging at a certain point. Come on the server I will show you.

**Comment by Violat0r** [comment]
Nevermind that drop off is really small is the issue.

**Comment by Violat0r** [comment]
One or two feet in game is when the drop off happens then no damage from a long ways away.

**Comment by Zaratusa** [comment]
Ok should be fine now, I've decluttered the code and have set up a simpler way to modify the deadly range.
